# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(name: "Jarno", password: "spoopy")
User.create(name: "Simperella", password: "spoopy")
User.create(name: "Poushtart", password: "spoopy")
User.create(name: "CaNdYcAnE748", password: "spoopy")
User.create(name: "racketball6868", password: "spoopy")
User.create(name: "PeplosKore", password: "spoopy")
User.create(name: "obeocookiE", password: "spoopy")
User.create(name: "Ranaferboi", password: "spoopy")
User.create(name: "JolenejoleneJOLEEENE", password: "spoopy")
User.create(name: "password123", password: "justkidding")
User.create(name: "Guest", password: "123456")
User.create(name: "Troll", password: "lololxd")

Meme.create(url: "www.spoopry.com/cat.jpg", title: "Cat", user_id: 1)
Meme.create(url: "www.soopry.com/dog.jpg", title: "Dog", user_id: 2)
Meme.create(url: "www.oolalala.com/meme.jpg", title: "SO FUNNY L0L", user_id: 3)
Meme.create(url: "www.spopryfo.com/halaa.jpg", title: "hieeee", user_id: 4)
Meme.create(url: "www.foslaspoopry.com/luke.jpg", title: "star war", user_id: 5)
Meme.create(url: "www.spoopry.com/handsome.jpg", title: "mansome", user_id: 1)
Meme.create(url: "www.soprrymom.com/fifth.jpg", title: "FREE SPEECH 5EVER", user_id: 4)
Meme.create(url: "www.27gag.com/blargh.jpg", title: "ladsfkj", user_id: 5)
Meme.create(url: "www.3squaredgag.com/jarno.jpg", title: "Jarno is a secret character", user_id: 2)
Meme.create(url: "www.3agapple.com/jarno.jpg", title: "luluguthackednub", user_id: 9, attribution: "https://www.10thousandgig.com")
Meme.create(url: "www.thighsanddrumbstixx.co.uk/chxnprmsn.jpg", title: "Chicken Parmesan is a secret Character", user_id: 1)
Meme.create(url: "www.panshmina.com/jo.jpg", title: "Seen at the terminal", user_id: 1)

Comment.create(user_id: 2, meme_id: 1, body: "lul 2 gud")
Comment.create(user_id: 1, meme_id: 1, body: "lul 3 gud")
Comment.create(user_id: 2, meme_id: 1, body: "LUL 4 GUD!!!!!!!!")
Comment.create(user_id: 3, meme_id: 1, body: "stfu losers also first comment")
Comment.create(user_id: 4, meme_id: 1, body: "I just made $65 in 20 seconds at www.fr33 ph4rm4z00t1culz.nz!")
Comment.create(user_id: 5, meme_id: 1, body: "wtf spambot gtfo... to my room")
Comment.create(user_id: 6, meme_id: 1, body: "This morning I went to go pick up my milk from the milkman who delivered it to my doorstep and I went outside and itl ooked like this cat had already been there it it looked just like thid one!!!! right nancy??")
Comment.create(user_id: 7, meme_id: 2, body: "haha i can't even get out of bed wifout doin dis once")
Comment.create(user_id: 8, meme_id: 3, body: "NEGAVERSE FOREVER. TEAM BERYL FROM BEYOND THE DARKNESS.")
Comment.create(user_id: 1, meme_id: 4, body: "Wenty went to the mall and bought this once.")
Comment.create(user_id: 2, meme_id: 3, body: "dis is a symbol of soceity todei")
Comment.create(user_id: 3, meme_id: 3, body: "What part of it?")
Comment.create(user_id: 2, meme_id: 3, body: "the dumb parte?")
Comment.create(user_id: 3, meme_id: 3, body: "Can you elaborate further? I don't understand.")
Comment.create(user_id: 2, meme_id: 3, body: "lyke the wei it wud be if wede work together it'd be wei better den now lyke in dis meme")
Comment.create(user_id: 3, meme_id: 3, body: "What would be better than today? We have running water, the sun is shining, and God is watching over the USA.")
Comment.create(user_id: 2, meme_id: 3, body: "lol nvm u just dun get it ;P")
Comment.create(user_id: 3, meme_id: 3, body: "I'm sincerely trying to understand what you're trying to say.")
Comment.create(user_id: 4, meme_id: 1, body: "I just made $65 in 20 seconds at www.fr33 ph4rm4z00t1culz.nz!")
Comment.create(user_id: 4, meme_id: 2, body: "I just made $65 in 20 seconds at www.fr33 ph4rm4z00t1culz.nz!")
Comment.create(user_id: 4, meme_id: 3, body: "I just made $65 in 20 seconds at www.fr33 ph4rm4z00t1culz.nz!")
Comment.create(user_id: 4, meme_id: 4, body: "I just made $65 in 20 seconds at www.fr33 ph4rm4z00t1culz.nz!")
Comment.create(user_id: 4, meme_id: 5, body: "I just made $65 in 20 seconds at www.fr33 ph4rm4z00t1culz.nz!")
Comment.create(user_id: 4, meme_id: 6, body: "I just made $65 in 20 seconds at www.fr33 ph4rm4z00t1culz.nz!")
Comment.create(user_id: 4, meme_id: 7, body: "I just made $65 in 20 seconds at www.fr33 ph4rm4z00t1culz.nz!")
Comment.create(user_id: 4, meme_id: 8, body: "I just made $65 in 20 seconds at www.fr33 ph4rm4z00t1culz.nz!")
Comment.create(user_id: 4, meme_id: 9, body: "I just made $65 in 20 seconds at www.fr33 ph4rm4z00t1culz.nz!")
Comment.create(user_id: 6, meme_id: 5, body: "my son in law has hair just like that on his back!! ha ha ha!")
Comment.create(user_id: 1, meme_id: 6, body: "~Swingin in the backyard pull up in your fast car whistlin mah name~")
Comment.create(user_id: 2, meme_id: 7, body: "holy christ protect us sinners")
Comment.create(user_id: 3, meme_id: 7, body: "I'm well watered like a horse")
Comment.create(user_id: 9, meme_id: 8, body: "I got dead person hands. SQUAWK! -John Everdeen")

Tagname.create(tagname: "Jurples")
Tagname.create(tagname: "Cat")
Tagname.create(tagname: "Wenty")
Tagname.create(tagname: "Horrible")
Tagname.create(tagname: "NSFW")
Tagname.create(tagname: "Dog")

Tag.create(meme_id: 1, tagname_id: 1)
Tag.create(meme_id: 2, tagname_id: 1)
Tag.create(meme_id: 4, tagname_id: 1)
Tag.create(meme_id: 5, tagname_id: 1)
Tag.create(meme_id: 7, tagname_id: 2)
Tag.create(meme_id: 6, tagname_id: 2)
Tag.create(meme_id: 5, tagname_id: 2)
Tag.create(meme_id: 4, tagname_id: 2)
Tag.create(meme_id: 3, tagname_id: 2)
Tag.create(meme_id: 8, tagname_id: 2)
Tag.create(meme_id: 1, tagname_id: 3)
Tag.create(meme_id: 3, tagname_id: 3)
Tag.create(meme_id: 4, tagname_id: 3)
Tag.create(meme_id: 5, tagname_id: 3)
Tag.create(meme_id: 6, tagname_id: 3)
Tag.create(meme_id: 7, tagname_id: 3)
Tag.create(meme_id: 8, tagname_id: 3)
Tag.create(meme_id: 2, tagname_id: 4)
Tag.create(meme_id: 3, tagname_id: 4)
Tag.create(meme_id: 5, tagname_id: 4)
Tag.create(meme_id: 6, tagname_id: 4)
Tag.create(meme_id: 7, tagname_id: 4)
Tag.create(meme_id: 8, tagname_id: 4)
Tag.create(meme_id: 9, tagname_id: 4)
Tag.create(meme_id: 4, tagname_id: 5)
Tag.create(meme_id: 5, tagname_id: 5)
Tag.create(meme_id: 6, tagname_id: 5)
Tag.create(meme_id: 2, tagname_id: 6)
Tag.create(meme_id: 3, tagname_id: 6)
Tag.create(meme_id: 4, tagname_id: 6)
Tag.create(meme_id: 5, tagname_id: 6)
Tag.create(meme_id: 6, tagname_id: 6)

Vote.create(votable_type: "Meme", votable_id: 1, vote_val: 1, user_id: 1)
Vote.create(votable_type: "Meme", votable_id: 1, vote_val: 1, user_id: 2)
Vote.create(votable_type: "Meme", votable_id: 1, vote_val: 1, user_id: 3)
Vote.create(votable_type: "Meme", votable_id: 1, vote_val: 1, user_id: 4)
Vote.create(votable_type: "Meme", votable_id: 1, vote_val: 1, user_id: 5)
Vote.create(votable_type: "Meme", votable_id: 1, vote_val: 1, user_id: 6)
Vote.create(votable_type: "Meme", votable_id: 1, vote_val: 1, user_id: 7)
Vote.create(votable_type: "Meme", votable_id: 1, vote_val: 1, user_id: 8)
Vote.create(votable_type: "Meme", votable_id: 1, vote_val: 1, user_id: 9)
Vote.create(votable_type: "Meme", votable_id: 2, vote_val: 1, user_id: 1)
Vote.create(votable_type: "Meme", votable_id: 2, vote_val: 1, user_id: 2)
Vote.create(votable_type: "Meme", votable_id: 2, vote_val: 1, user_id: 3)
Vote.create(votable_type: "Meme", votable_id: 2, vote_val: 1, user_id: 4)
Vote.create(votable_type: "Meme", votable_id: 2, vote_val: 1, user_id: 5)
Vote.create(votable_type: "Meme", votable_id: 2, vote_val: 1, user_id: 6)
Vote.create(votable_type: "Meme", votable_id: 2, vote_val: -1, user_id: 7)
Vote.create(votable_type: "Meme", votable_id: 2, vote_val: -1, user_id: 8)
Vote.create(votable_type: "Meme", votable_id: 2, vote_val: -1, user_id: 9)
Vote.create(votable_type: "Meme", votable_id: 3, vote_val: -1, user_id: 1)
Vote.create(votable_type: "Meme", votable_id: 3, vote_val: -1, user_id: 2)
Vote.create(votable_type: "Meme", votable_id: 3, vote_val: -1, user_id: 3)
Vote.create(votable_type: "Meme", votable_id: 3, vote_val: -1, user_id: 4)
Vote.create(votable_type: "Meme", votable_id: 3, vote_val: -1, user_id: 5)
Vote.create(votable_type: "Meme", votable_id: 3, vote_val: -1, user_id: 6)
Vote.create(votable_type: "Meme", votable_id: 3, vote_val: -1, user_id: 7)
Vote.create(votable_type: "Meme", votable_id: 3, vote_val: -1, user_id: 8)
Vote.create(votable_type: "Meme", votable_id: 3, vote_val: -1, user_id: 9)
Vote.create(votable_type: "Meme", votable_id: 4, vote_val: -1, user_id: 1)
Vote.create(votable_type: "Meme", votable_id: 4, vote_val: -1, user_id: 2)
Vote.create(votable_type: "Meme", votable_id: 4, vote_val: -1, user_id: 3)
Vote.create(votable_type: "Meme", votable_id: 4, vote_val: -1, user_id: 4)
Vote.create(votable_type: "Meme", votable_id: 4, vote_val: -1, user_id: 5)
Vote.create(votable_type: "Meme", votable_id: 4, vote_val: -1, user_id: 6)
Vote.create(votable_type: "Meme", votable_id: 4, vote_val: -1, user_id: 7)
Vote.create(votable_type: "Meme", votable_id: 4, vote_val: -1, user_id: 8)
Vote.create(votable_type: "Meme", votable_id: 5, vote_val: 1, user_id: 1)
Vote.create(votable_type: "Meme", votable_id: 5, vote_val: 1, user_id: 2)
Vote.create(votable_type: "Meme", votable_id: 5, vote_val: 1, user_id: 3)
Vote.create(votable_type: "Meme", votable_id: 5, vote_val: 1, user_id: 4)
Vote.create(votable_type: "Meme", votable_id: 5, vote_val: -1, user_id: 5)
Vote.create(votable_type: "Meme", votable_id: 5, vote_val: -1, user_id: 6)
Vote.create(votable_type: "Meme", votable_id: 5, vote_val: -1, user_id: 7)
Vote.create(votable_type: "Meme", votable_id: 6, vote_val: 1, user_id: 1)
Vote.create(votable_type: "Meme", votable_id: 6, vote_val: 1, user_id: 2)
Vote.create(votable_type: "Meme", votable_id: 6, vote_val: 1, user_id: 3)
Vote.create(votable_type: "Meme", votable_id: 6, vote_val: 1, user_id: 4)
Vote.create(votable_type: "Meme", votable_id: 6, vote_val: 1, user_id: 5)
Vote.create(votable_type: "Meme", votable_id: 6, vote_val: 1, user_id: 6)
Vote.create(votable_type: "Meme", votable_id: 6, vote_val: 1, user_id: 7)
Vote.create(votable_type: "Meme", votable_id: 6, vote_val: 1, user_id: 8)
Vote.create(votable_type: "Meme", votable_id: 7, vote_val: 1, user_id: 1)
Vote.create(votable_type: "Meme", votable_id: 7, vote_val: 1, user_id: 2)
Vote.create(votable_type: "Meme", votable_id: 7, vote_val: 1, user_id: 3)
Vote.create(votable_type: "Meme", votable_id: 7, vote_val: 1, user_id: 4)
Vote.create(votable_type: "Meme", votable_id: 7, vote_val: -1, user_id: 5)
Vote.create(votable_type: "Meme", votable_id: 7, vote_val: -1, user_id: 6)
Vote.create(votable_type: "Meme", votable_id: 8, vote_val: -1, user_id: 1)
Vote.create(votable_type: "Meme", votable_id: 8, vote_val: -1, user_id: 2)
Vote.create(votable_type: "Meme", votable_id: 8, vote_val: -1, user_id: 3)
Vote.create(votable_type: "Meme", votable_id: 8, vote_val: -1, user_id: 4)
Vote.create(votable_type: "Meme", votable_id: 8, vote_val: -1, user_id: 5)
Vote.create(votable_type: "Meme", votable_id: 8, vote_val: -1, user_id: 6)
Vote.create(votable_type: "Meme", votable_id: 8, vote_val: -1, user_id: 7)
Vote.create(votable_type: "Meme", votable_id: 8, vote_val: -1, user_id: 8)
Vote.create(votable_type: "Meme", votable_id: 9, vote_val: 1, user_id: 1)
Vote.create(votable_type: "Meme", votable_id: 9, vote_val: 1, user_id: 2)
Vote.create(votable_type: "Meme", votable_id: 9, vote_val: 1, user_id: 3)
